# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: SNAPSHOT Build

on:
  push:
    branches: [ master ]

jobs:
  linux:
    if: "!contains(github.event.head_commit.message, 'cd skip')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build JAR dist files
      run: ./gradlew dist
    - name: Build deb package
      run: ./gradlew jpackage
    - name: Fix deb file names
      run: mv build/jpackage/*.deb HyperLap2D-SNAPSHOT.deb
    - name: Upload deb artifact
      uses: actions/upload-artifact@v2
      with:
        name: HyperLap2D-SNAPSHOT.deb
        path: HyperLap2D-SNAPSHOT.deb
    - name: Fix libgdx-spine-extension file names
      run: mv h2d-libgdx-spine-extension/build/libs/*.jar h2d-libgdx-spine-extension-SNAPSHOT.jar
    - name: Upload libgdx-spine-extension artifact
      uses: actions/upload-artifact@v2
      with:
        name: h2d-libgdx-spine-extension-SNAPSHOT.jar
        path: h2d-libgdx-spine-extension-SNAPSHOT.jar
    - name: Fix runtime-libgdx file names
      run: mv hyperlap2d-runtime-libgdx/build/libs/*.jar hyperlap2d-runtime-libgdx-SNAPSHOT.jar
    - name: Upload hyperlap2d-runtime-libgdx artifact
      uses: actions/upload-artifact@v2
      with:
        name: hyperlap2d-runtime-libgdx-SNAPSHOT.jar
        path: hyperlap2d-runtime-libgdx-SNAPSHOT.jar
    - name: Fix hyperlap2d-common-api names
      run: mv hyperlap2d-common-api/build/libs/*.jar hyperlap2d-common-api-SNAPSHOT.jar
    - name: Upload hyperlap2d-common-api artifact
      uses: actions/upload-artifact@v2
      with:
        name: hyperlap2d-common-api-SNAPSHOT.jar
        path: hyperlap2d-common-api-SNAPSHOT.jar

  windows:
    if: "!contains(github.event.head_commit.message, 'cd skip')"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build JAR dist files
      run: ./gradlew.bat dist
    - name: Build msi package
      run: ./gradlew.bat jpackage
    - name: Fix file names
      run: mv build/jpackage/*.msi HyperLap2D-SNAPSHOT.msi
    - name: Upload msi artifact
      uses: actions/upload-artifact@v2
      with:
        name: HyperLap2D-SNAPSHOT.msi
        path: HyperLap2D-SNAPSHOT.msi

  macOS:
    if: "!contains(github.event.head_commit.message, 'cd skip')"
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build JAR dist files
      run: ./gradlew dist
    - name: Build dmg package
      run: ./gradlew jpackage
    - name: Fix file names
      run: mv build/jpackage/*.dmg HyperLap2D-SNAPSHOT.dmg
    - name: Upload dmg artifact
      uses: actions/upload-artifact@v2
      with:
        name: HyperLap2D-SNAPSHOT.dmg
        path: HyperLap2D-SNAPSHOT.dmg
